# Generated by Django 4.0.1 on 2022-01-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='dogs',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='owners',
        ),
    ]
