# Generated by Django 4.0.1 on 2022-01-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_dog_table_alter_owner_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
