# Generated by Django 4.0.1 on 2022-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
